### ISSUE TITLE
Not working while using start and end times(Embed URL).

### ISSUE THREAD

**Issue by FaheemAnsariReal** [mpb10/PowerShell-Youtube-dl#15]
Hi,

The script is not properly working while giving it embed url, its downloading entire video while it has to download only from start to end time vides.

Example: https://www.youtube.com/embed/A48pm46zyTw?start=80&end=160&version=3

Please test and let me know how can I do that, rest its amazing.

Thanks

**Comment by mpb10** [comment]
Hello,

Unfortunately, there isn't a way to use the Youtube URL provided start and end times. You'll have to have youtube-dl download the entire video and then use ffmpeg to trim the video to the desired times. This can be done using this script by editing some of the script variable settings in the 'youtube-dl.ps1' file.

On line 91, change the $ConvertFile value to $True.
On line 96, change the $StartTime value to "-ss hh:mm:ss" where hh is the hour, mm is the minutes, and ss is the seconds (Ex: "-ss 00:01:20").
On line 97, change the $StopTime value to "-to hh:mm:ss" where hh is the hour, mm is the minutes, and ss is the seconds (EX: "-to 00:02:40")

Save the values, download the video, and it should trim the video to those times. After you're done, don't forget to change the $ConvertFile value back to $False. Let me know how it goes!

**Comment by FaheemAnsariReal** [comment]
Hi Mpb10,

I've tried, but the results are not proper. Here is what I get:
1 to 5
1:39 to almost 5:00
>tried cutting 1 minute but only got 2 second of video and it starts with 1:33 which means 33 second delay
>tried cutting from 1:00 to 4:00, got only 3 minute of video which start from 1:33.

It does cuts the videos but not exact.

Can you please check/update the code to return exact time video, if yes I've an great idea to make it as bulk video cutting program. Me too a PowerShell developer, will update it as a bulk video cutter with automation.

Please test and let me know if its returning actual trimmed video without delay. It should work even if we require 1 second of video.

Thanks for your help.

**Comment by mpb10** [comment]
This is likely an issue with youtube-dl itself. I would recommend updating the youtube-dl executable.
