### ISSUE TITLE
Large Video Files Won't Save On FAT32 Drives

### ISSUE THREAD

**Issue by adam-savard** [mpb10/PowerShell-Youtube-dl#16]
When downloading a file over 4GB (the maximum file size) on a FAT32 partitioned drive, the file will not save and instead you'll get an error that says the disk is full. A couple of suggestions:

- Warn the user about FAT32 partitions during setup
- Split files at the 4GB mark

**Comment by mpb10** [comment]
Sorry for not writing back sooner. Good catch. I'll make a note of this in the next version that I've been working on. The readme should be more clear and concise, and this information will be good for a `problems/issues` section.

I checked youtube-dl's documentation and it looks like there isn't an easy way to split files at a certain size or stop a download at a certain file size. I could only find the `--max-filesize <size>` option which just skips videos that are larger than the specified size. I'll look into this a little bit more later, but you may be out of luck in regards to downloading large videos to FAT32 drives.
