### ISSUE TITLE
Is this Dead?  FFMPEG update fails.

### ISSUE THREAD

**Issue by TheSmashy** [mpb10/PowerShell-Youtube-dl#18]
https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip no longer works, anyone have a good URL for ffmpeg updates?

**Comment by mpb10** [comment]
unfortunately FFMPEG changed their download URLs. This should be fixed in the latest version of the script, `3.0.0`, which requires a re-install of the script.
